### ISSUE TITLE
subscriptions

### ISSUE THREAD

**Issue by mattearnshaw** [np1/mps-youtube#280] opened 2015-05-17 16:16 UTC
it would be nice to be able to "subscribe" to channels (without having a google account)
probably best done via the rss feeds
https://www.youtube.com/feeds/videos.xml?channel_id=UC...

cheers

**Comment by ids1024** [comment] 2015-05-17 16:21
Duplicate of #157.

**Closed by ids1024** 2015-05-17 16:21 UTC
