### ISSUE TITLE
choose codec

### ISSUE THREAD

**Issue by knezi** [np1/mps-youtube#286] opened 2015-05-19 15:56 UTC
Hi,
thanks for amazing player. I run it on RasPi and it unfortunately doesn't support VP9, so I can't play most of videos, even though there is also mp4 version available.
It would be nice to set in configuration, which codec will mpsyt play.
Thanks.

**Comment by ids1024** [comment] 2015-05-19 23:22
Duplicate of #71.

**Closed by ids1024** 2015-05-19 23:22 UTC

**Comment by knezi** [comment] 2015-05-20 05:52
Oh, I am sorry. I didn't look at this one - I have tried just search codec, not mp4.
