### ISSUE TITLE
Access my youtube subscription fee [feature request]

### ISSUE THREAD

**Issue by mguzmann** [np1/mps-youtube#233] opened 2015-03-25 16:53 UTC
It would be great if I could access my news fee from the cli. Is this possible?

**Comment by EduardoRT** [comment] 2015-03-31 20:45
It's not possible yet, it'll be cool though, and you do have an unique rss feed provided by youtube so the only thing needed will be parsing that rss into a playlist.

**Comment by ids1024** [comment] 2015-06-11 21:46
Duplicate of #157.

**Closed by ids1024** 2015-06-11 21:46 UTC
Labels: feature request
