### ISSUE TITLE
non latin1 character encoding errors

### ISSUE THREAD

**Issue by mpsyt-user** [np1/mps-youtube#296] opened 2015-05-29 20:31 UTC
hello np1, thanks for this great application!
when i want to to listen to non-english songs (latin-5 in particular) on mpsyt i get an error like this:

Problem playing last item: 'latin-1' codec can't encode characters in position 7-8: ordinal not in range(256)

if you could fix this it would be awesome

best wishes

**Comment by ids1024** [comment] 2015-05-30 20:14
What is the output of `mpsyt --version`?

**Comment by mpsyt-user** [comment] 2015-05-30 21:11
mpsyt version  : 0.2.4 
   notes       : released 13 May 2015
pafy version   : 0.3.72
Python version : 2.7.5 (default, May 29 2013, 03:26:28) 
[GCC 4.8.0]
Processor      : Intel(R) Core(TM) i5 CPU         760  @ 2.80GHz
Machine type   : i686
Architecture   : 32bit, ELF
Platform       : Linux-3.10.17-smp-i686-Intel-R-_Core-TM-_i5_CPU_________760__@_2.80GHz-with-slackware-14.1
sys.stdout.enc : ISO-8859-1
default enc    : ascii
Config dir     : /home/user/.config/mps-youtube
env:TERM       : rxvt-unicode-256color
env:SHELL      : /bin/bash
env:LANG       : en_US

**Comment by ids1024** [comment] 2015-05-31 03:53
This seems to be caused by using python 2. Try installing mpsyt with python 3.

**Comment by mpsyt-user** [comment] 2015-05-31 06:08
sorry that didn't work

**Comment by ids1024** [comment] 2015-05-31 16:42
Ok, I think I have this fixed in commit f37193a00a48ab93778e978a22c1ab72caeadf05 in the develop branch. You should be able to install it with this command:

    pip install --upgrade https://github.com/np1/pafy/archive/develop.zip https://github.com/np1/mps-youtube/archive/develop.zip

**Closed** 2015-06-01 23:51 UTC
Labels: bug, fix applied
