### ISSUE TITLE
Windows - UnicodeEncodeError: 'gbk' codec can't encode character u'\u04b6' in position 1303: illegal multibyte sequence

### ISSUE THREAD

**Issue by Alan-Peng** [np1/mps-youtube#174] opened 2014-12-26 14:20 UTC
Mps-youtube run on windows,Search error

Traceback (most recent call last):
File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "C:\Python27\lib\runpy.py", line 72, in _run_code
exec code in run_globals
File "C:\Python27\Scripts\mpsyt.exe\__main__.py", line 9, in <module>
File "C:\Python27\lib\site-packages\mps_youtube\main.py", line 4261, in main
screen_update()
File "C:\Python27\lib\site-packages\mps_youtube\main.py", line 1508, in screen_update
xprint(g.content)
File "C:\Python27\lib\site-packages\mps_youtube\main.py", line 150, in xprint
print(xenc(stuff), end=end)
UnicodeEncodeError: 'gbk' codec can't encode character u'\u04b6' in position 1303: illegal multibyte sequence

**Comment by np1** [comment] 2015-01-04 11:31
Hi, is this when you search for something in particular or does it occur with all searches?

What is the output of running `mpsyt --version` ?

**Comment by Alan-Peng** [comment] 2015-01-04 12:55
mpsyt version  : 0.2.1
pafy version   : 0.3.66
Python version : 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]
Processor      : Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
Machine type   : AMD64
Architecture   : 32bit, WindowsPE
Platform       : Windows-8-6.2.9200
sys.stdout.enc : cp936
default enc    : ascii

**Comment by np1** [comment] 2015-01-04 14:49
Thank you. Does the error appear when you enter a specific search term and if so can you state which search query produces the error?

**Comment by Alan-Peng** [comment] 2015-01-04 14:52
Chinese，and Search results appear in Chinese。
My English is not good。

**Comment by ids1024** [comment] 2015-01-14 05:29
@np1 I think the problem is in this line.  Isn't this trying to decode gbk as though it were Utf-8?

     txt = txt.encode(sse, "replace").decode("utf8", "ignore")

I think the line should be like this, but I haven't done any testing:

     txt = txt.encode(sse, "replace").decode(sse)

**Comment by ids1024** [comment] 2015-05-31 21:32
I pushed the fix above in f37193a00a48ab93778e978a22c1ab72caeadf05, which resolved what appears to be the same issue (#296).

**Closed** 2015-06-01 23:52 UTC
Labels: bug, fix applied
