### ISSUE TITLE
No Search Results Returned

### ISSUE THREAD

**Issue by elcantantedeloscantantes** [np1/mps-youtube#179] opened 2015-01-08 20:35 UTC
I recently installed mps-youtube using homebrew. A fter starting up mps-youtube and using the search function, no results are returned.  The default settings are what I am using, and I have mplayer installed.  

Is there some common/obvious parameter that I have not configured correctly, or something I might need to install that may not be installed on my machine?

I assume this will be a very easy thing to solve, I apologize for asking about something so stupid.

**Comment by np1** [comment] 2015-01-08 22:11
What is the output of `mps-youtube --version` ?  Is there any message when no search results are returned?

**Comment by elcantantedeloscantantes** [comment] 2015-01-09 00:10
I launch mps-youtube with the command 'mpsyt' from the terminal, and it starts fine.  Once open, I type the following command:

'/searchterm'

and press the return key.  The software just prints the following text:

"Found nothing for 'searchterm'"

I have entered several things for the text referred to above as 'searchterm', things that would certainly return many results (music, elton john, aaaa, etc).  

This is the only output I get.  The software seems to work fine, I just get no results when searching for content.

Thank you!

**Comment by elcantantedeloscantantes** [comment] 2015-01-09 00:12
Ahh I forgot to include the output of the 'mps-youtube --version' command, it is below:


mpsyt --version

mpsyt version  : 0.2.1 
pafy version   : 0.3.66
Python version : 2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:15:42) 
[GCC 4.2.1 (Apple Inc. build 5577)]
Processor      : i386
Machine type   : i386
Architecture   : 32bit, 
Platform       : Darwin-10.8.0-i386-32bit
sys.stdout.enc : UTF-8
default enc    : ascii
env:TERM       : screen
env:SHELL      : /bin/bash
env:LANG       : en_US.UTF-8

**Comment by np1** [comment] 2015-01-09 00:36
hmm, may be a connectivity issue. Do you connect to the internet through a proxy?

What is the output of this command:
`python -c "import urllib2;print(len(urllib2.urlopen('https://youtube.com').read()))"`

**Comment by elcantantedeloscantantes** [comment] 2015-01-09 01:32
I do not connect through a proxy.  I am able to connect to the website (youtube site), and I have a good internet connection.  I have used both an ethernet connection and wireless internet.  Below is the output of the command you posted above:

python -c "import urllib2;print(len(urllib2.urlopen('https://youtube.com').read()))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>

**Comment by np1** [comment] 2015-01-09 02:09
Thanks, Python is not able to access https://youtube.com on your system which is why there is a problem.

It looks to be due to a recent change released in Python 2.7.9 [HTTPS certificate validation using the system's certificate store is now enabled by default.](https://www.python.org/downloads/release/python-279/)

There are some [workarounds](https://www.python.org/dev/peps/pep-0476/#backwards-compatibility) that I could implement - although I believe it would be better to get the certificate validation to work as intended.

Perhaps you need to update your system ssl certificates although I don't know how to do that and can't be sure it would fix the problem :( I will have to look into it more and get back to you unless anyone else can shed more light?

**Comment by elcantantedeloscantantes** [comment] 2015-01-09 02:11
Hmm should I just try to use another version of Python?

Thank you for your help!

**Comment by np1** [comment] 2015-01-09 02:19
It's not an ideal solution but yes, I expect an older version of Python would not have this issue.

**Comment by elcantantedeloscantantes** [comment] 2015-01-09 02:28
I am using an older version now, it works fine.  This is such a great idea (mpsyt in general), I really love it hahaha thank you for your help.

**Closed** 2015-02-14 07:02 UTC

**Comment by jrenner** [comment] 2015-05-06 20:08
I'm experiencing this with Python 3.4.3
