### ISSUE TITLE
Video never plays in a better quality than 1280x720

### ISSUE THREAD

**Issue by Nordic89** [np1/mps-youtube#238] opened 2015-04-02 09:32 UTC
Trying to play a video with a 4k resolution, but it plays a 1280x720 instead, despite setting max_res to 2160p.

[code]
WARNING:root:Unknown itag: 313
[/code]
This is the warning I get before it happens

**Comment by ids1024** [comment] 2015-04-05 15:50
Duplicate of issue #151.

**Closed** 2015-04-05 21:01 UTC
Labels: duplicate
