### ISSUE TITLE
mpsyt failure HTTP Error 503

### ISSUE THREAD

**Issue by spvkgn** [np1/mps-youtube#300] opened 2015-05-31 16:27 UTC
Seems like there is a bug with latest dev version. It occurs when mpsyt trying to launch next scheduled video in playlist.

```
Traceback (most recent call last):                                                                                                                           
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 2101, in playsong
    get_streams(song, force=failcount, callback=writestatus)
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 345, in get_streams
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 314, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/local/lib/python3.2/dist-packages/pafy/pafy.py", line 137, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/local/lib/python3.2/dist-packages/pafy/pafy.py", line 1068, in __init__
    self.fetch_basic()
  File "/usr/local/lib/python3.2/dist-packages/pafy/pafy.py", line 1111, in fetch_basic
    self.dash = _extract_dash(self._dashurl)
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.2/urllib/request.py", line 413, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.2/urllib/request.py", line 347, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.2/urllib/request.py", line 495, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 2101, in playsong
    get_streams(song, force=failcount, callback=writestatus)
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 345, in get_streams
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 314, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/local/lib/python3.2/dist-packages/pafy/pafy.py", line 137, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/local/lib/python3.2/dist-packages/pafy/pafy.py", line 1068, in __init__
    self.fetch_basic()
  File "/usr/local/lib/python3.2/dist-packages/pafy/pafy.py", line 1111, in fetch_basic
    self.dash = _extract_dash(self._dashurl)
  File "/usr/local/lib/python3.2/dist-packages/pafy/pafy.py", line 294, in _extract_dash
    dashdata = fetch_decode(dashurl)
  File "/usr/local/lib/python3.2/dist-packages/pafy/pafy.py", line 90, in fetch_decode
    req = g.opener.open(url)
  File "/usr/lib/python3.2/urllib/request.py", line 375, in open
    response = meth(req, response)
  File "/usr/lib/python3.2/urllib/request.py", line 487, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.2/urllib/request.py", line 413, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.2/urllib/request.py", line 347, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.2/urllib/request.py", line 495, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 2101, in playsong
    get_streams(song, force=failcount, callback=writestatus)
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 345, in get_streams
    get_streams(song, force=failcount, callback=writestatus)
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 345, in get_streams
    p = get_pafy(vid, force=force, callback=callback)
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 314, in get_pafy
    p = pafy.new(item.ytid, callback=callback_fn)
  File "/usr/local/lib/python3.2/dist-packages/pafy/pafy.py", line 137, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/local/lib/python3.2/dist-packages/pafy/pafy.py", line 1068, in __init__
    self.fetch_basic()
  File "/usr/local/lib/python3.2/dist-packages/pafy/pafy.py", line 1111, in fetch_basic
    self.dash = _extract_dash(self._dashurl)
  File "/usr/local/lib/python3.2/dist-packages/pafy/pafy.py", line 294, in _extract_dash
    dashdata = fetch_decode(dashurl)
  File "/usr/local/lib/python3.2/dist-packages/pafy/pafy.py", line 90, in fetch_decode
    req = g.opener.open(url)
  File "/usr/lib/python3.2/urllib/request.py", line 375, in open
    response = meth(req, response)
  File "/usr/lib/python3.2/urllib/request.py", line 487, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.2/urllib/request.py", line 413, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.2/urllib/request.py", line 347, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.2/urllib/request.py", line 495, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 9, in <module>
    load_entry_point('mps-youtube==0.2.4', 'console_scripts', 'mpsyt')()
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 4771, in main
    if matchfunction(k, v, userinput):
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 4666, in matchfunction
    func(*matches)
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 3447, in play_all
    play(options, "1-" + str(len(g.model.songs)))
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 3441, in play
    play_range(songlist, shuffle, repeat, override)
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 3534, in play_range
    returncode = playsong(song, override=override)
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 2113, in playsong
    return playsong(song, failcount=failcount, override=override)
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 2113, in playsong
    return playsong(song, failcount=failcount, override=override)
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 2113, in playsong
    return playsong(song, failcount=failcount, override=override)
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 2125, in playsong
    cmd, songdata = generate_real_playerargs(song, override, failcount)
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/main.py", line 1997, in generate_real_playerargs
    q, audio, cached = failcount, not video, g.streams[song.ytid]
KeyError: 'PhIjrDxGqQw'
```

```
~ $ mpsyt --debug

mpsyt version  : 0.2.5-dev 
   notes       : development version
pafy version   : 0.3.72
Python version : 3.2.3 (default, Feb 27 2014, 21:33:50) 
[GCC 4.6.3]
Processor      : i686
Machine type   : i686
Architecture   : 32bit, ELF
Platform       : Linux-3.2.0-79-generic-pae-i686-with-LinuxMint-13-maya
sys.stdout.enc : UTF-8
default enc    : utf-8
Config dir     : /home/pavel/.config/mps-youtube
env:TERM       : screen-256color
env:SHELL      : /bin/bash
env:LANG       : ru_RU.UTF-8
```

**Comment by Atlantic777** [comment] 2015-05-31 16:49
I'm experiencing the same bug. The funny thing is that it's not repeatable.

- I tried to play one playlist and it failed on the first video.
- I tried again and it actually started fine and even continued to next video.
- When it crashed again, it didn't work even on the first video.
- When I tried to seek forward and let it continue to next video it was ok for few times and then crashed again.

I would say that it's a problem with API wrapper. Do we all use the same API keys or they are generated somehow automatically on install?

Traceback: https://gist.github.com/ef73c76383e7959b407f.git

```
mpsyt --debug

mpsyt version  : 0.2.5-dev 
   notes       : development version
pafy version   : 0.3.72
Python version : 3.4.0 (default, Apr 11 2014, 13:05:11) 
[GCC 4.8.2]
Processor      : x86_64
Machine type   : x86_64
Architecture   : 64bit, ELF
Platform       : Linux-3.13.0-39-generic-x86_64-with-Ubuntu-14.04-trusty
sys.stdout.enc : UTF-8
default enc    : utf-8
Config dir     : /home/nikola/.config/mps-youtube
env:TERM       : rxvt-unicode-256color
env:SHELL      : /usr/bin/fish
env:LANG       : en_US.UTF-8
env:LANGUAGE   : en_US
```

**Comment by ids1024** [comment] 2015-05-31 16:55
This seems to be a bug in https://github.com/np1/pafy

I have noticed error messages like this (and a couple others) happening randomly in pafy. I haven't found the cause, but it seems to be in the dash code.

If it weren't for this issue I would have released a new pafy version by now, and probably a new mpsyt release after that.

**Comment by ids1024** [comment] 2015-05-31 23:53
The 503 errors should be fixed in the pafy develop branch.

**Closed** 2015-06-03 04:18 UTC
Labels: bug, fix applied, released
