### ISSUE TITLE
[Feature request] Set video format

### ISSUE THREAD

**Issue by kilbith** [np1/mps-youtube#158] opened 2014-11-28 13:57 UTC
Hi there,

I'd like to set a video format such as mp4 for all the videos that I open.

The reason is that I use your program on Raspberry Pi and omxplayer is only decent video player on this (webm format is not supported and mplayer is badly slow on RPi).

Cheers, and keep up the good work !

**Comment by np1** [comment] 2015-01-04 14:46
Duplicate of #71

**Closed by np1** 2015-01-04 14:46 UTC
Labels: duplicate, feature request
